### ISSUE TITLE
Error 'Explicit valence for atom'

### ISSUE THREAD

**Issue by kolmorgan** [tiantz17/MolSHAP#4]
Hi,
Thanks for your Nice work. 
I'm trying to build my own model with some ligands. However, no matter what kind of software I use(including chemdraw and Chem3D) to create smiles file, the valence error keep appears, and I don't know how to solve this problem, Please help me.
example molecule: O=C(Nc1cccc(CC(O)(C(=O)O)[C@H]2CCNC2)c1)Nc1cccc(CC(O)(C(=O)O)[C@H]2CCNC2)c1
Error message
`Model training
[15:51:11] Explicit valence for atom # 3 C, 5, is greater than permitted
Traceback (most recent call last):
  File "molshap.py", line 163, in <module>
    molshap.train_onehot(ori_idx[train_idx], y_ori[train_idx])
  File "/home/wsr/MolSHAP-master/model.py", line 51, in train_onehot
    list_mol = [makebond(item)[0] for item in self.list_frag_mol[ori_idx]]        
  File "/home/wsr/MolSHAP-master/model.py", line 51, in <listcomp>
    list_mol = [makebond(item)[0] for item in self.list_frag_mol[ori_idx]]        
  File "/home/wsr/MolSHAP-master/utils.py", line 145, in makebond
    newmol.UpdatePropertyCache()
rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 3 C, 5, is greater than permitted`

segmentation fault also appears.
Thanks!

**Comment by tiantz17** [comment]
Currently, MolSHAP only supports analyzing ligands that share a common scaffold. Can you provide the scaffold structure you selected?

**Comment by kolmorgan** [comment]
The scaffold structure selected is 'O=C(O)[C@@H](Cc1ccccc1)[C@H]1CCNC1', and my molecules (e.g. AA) are a combination of scaffold structures (which is two units (two molecule A) linked via ethyl group on the phenyl ring) and substituted with its R-ring or linker of AA, which can be categorized into multivalence ligands. Therefore, maybe that is the reason why it failed?
Moreover, can the number of processors used be adjusted? I did the model analyzing with 10 molecules of my own and only one processor was used, so is there any way to accelerate the process like increasing the number of processors to be used? I'm not an expert in Python. Thank you!

**Comment by tiantz17** [comment]
You are right, only one scaffold structure is allowed for analyzing. As for speed up, the shap package does not support multiple processors. The overall time cost for demo is just 1~2 minutes so we did not consider accelerating.
